# Generated by Django 4.2.11 on 2024-04-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название дома объекта')),
                ('status', models.CharField(choices=[('Economy', 'Эконом'), ('Comfort', 'Комфорт'), ('Business', 'Бизнес'), ('Premium', 'Премиум')], max_length=10, verbose_name='Статус объекта')),
                ('floors', models.IntegerField(verbose_name='Этажность')),
                ('apartments_count', models.IntegerField(verbose_name='Количество квартир')),
                ('entrances_count', models.IntegerField(verbose_name='Количество подъездов')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Объект ЖК',
                'verbose_name_plural': 'Объекты ЖК',
            },
        ),
        migrations.CreateModel(
            name='SalesManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('deals_count', models.PositiveIntegerField(default=0, verbose_name='Количество сделок')),
                ('temporary_password', models.CharField(max_length=50, verbose_name='Временный пароль')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер квартиры')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('type', models.CharField(choices=[('1-room 45sqm', '1-комнатная (45 кв.м)'), ('1-room Studio 55sqm', '1-комнатная студия (55 кв.м)'), ('2-room 65sqm', '2-комнатная (65 кв.м)'), ('2-room Studio 75sqm', '2-комнатная студия (75 кв.м)'), ('3-room 85sqm', '3-комнатная (85 кв.м)'), ('4-room 144sqm', '4-комнатная (144 кв.м)'), ('Penthouse', 'Пентхаус')], max_length=50, verbose_name='Тип квартиры')),
                ('booking_date', models.DateField(blank=True, null=True, verbose_name='Дата брони')),
                ('booking_status', models.CharField(choices=[('Active', 'Активная'), ('Booked', 'Бронь'), ('Sold', 'Куплено'), ('Barter', 'Бартер'), ('Installment', 'Рассрочка'), ('Cancelled', 'Отмена')], max_length=100, verbose_name='Статус брони')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('client', models.CharField(blank=True, max_length=100, null=True, verbose_name='Клиент')),
                ('housing_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nedvijimost.housingobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email адрес')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Номер телефона')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Менеджер отдела продаж')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удален')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
