# Generated by Django 4.2.11 on 2024-04-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nedvijimost', '0002_apartment_number_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='sales_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nedvijimost.salesmanager', verbose_name='Менеджер продаж'),
        ),
    ]
