# Generated by Django 4.2.11 on 2024-04-11 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nedvijimost', '0003_apartment_sales_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanager',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]