# Generated by Django 4.2.11 on 2024-04-11 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nedvijimost', '0004_salesmanager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanager',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
